### PR TITLE
Remove python dependency from vim plugins.

### PR DESCRIPTION
**Pull request by Raimondi**
The output of sdcv can be obtained using just built-in functions, so that's what this PR does. I'm not sure if python was used for a reason not covered by this PR, if so let me know to see how that can be handled.

### CODE REVIEW

**Comment by phongvcao** [comment]
@Raimondi Yes you are correct. I was originally using VimScript-only to get sdcv output and the original codes look something similar to what you're doing with this pull request. 

However, later on I realized that I want to decorate and align not only sdcv in Vim but also sdcv in Bash/Zsh, so that in case I want to do a quick lookup of one single word I don't have to fire Vim up or use vim -c.

Thus, beside outputing sdcv inside Vim, this Vim plugin also aims to integrate & colorize sdcv output on the shell (particularly Bash and Zsh). If you look at the README.md file you can see that. The stardict.py file has a function to output the output for Bash/Zsh and the output looks (but the colorization is different) exactly like in Vim. I grouped both output for Bash/Zsh and output for Vim inside one single stardict.py file for convenience later on in case sdcv changes their output format.

I know you may think that I am going against the "One Thing Done Well" philosophy here but the stardict.py file serves both "bosses": Vim and Shell (Bash/Zsh). 

I am planning on adding an option for users to choose whether they want to use VimScript (so no coloring for Bash/Zsh) or Python (including color support for Bash/Zsh).

Thank you for this nice Pull Request it looks even better than my original VimScript-only version. I am in the middle of house-moving period so I will get back to this in a week or so. 

Please keep watching the repo I will soon release the option. I will keep your Pull Request open till then :dancers:

**Comment by phongvcao** [comment]
@Raimondi the problem is I can use VimScript for sdcv output in Vim and Python for sdcv output in Bash/Zsh but like I said that may make things complicated/inconvenient when I have to change the colorization in case sdcv output changes.

Beside showing the output of sdcv in Vim, the stardict.py script:
(1) Adds proper indentation and/or corrects indentation of original sdcv output
(2) Formats sdcv output in a way that is easier to skim (changes original sdcv bullet points and colors)

If you try your Pull Request code above, the output shown in Vim is very similar to the original sdcv output, which sometimes can have wrong indentation and bad bullet points format. The reason I wrote this plugin was because I want sdcv output to look as nice as the GUI StarDict output, in both Vim and Bash/Zsh. 

Formatting/Colorizing the sdcv output in Python is, IMHO, a lot easier for me to maintain and debug than in VimScript, and I don't want to maintain/debug codes for 2 separate languages: VimScript and Python. So this plugin's aim is somewhat like Powerline: cross-application decoration & formatting.

If what you are looking for is simply display of sdcv output with no reformatting/colorization/indentation, you can look at the vim-sdcv plugin of chusiang at https://github.com/chusiang/vim-sdcv. I will consider using VimScript-only after finishing moving to my new house.

Stay tuned.

**Comment by Raimondi** [comment]
I see your point and I get it. Let me know if you need some help if/when you decide removing the +python requirement.

**Comment by phongvcao** [comment]
@Raimondi no problem see you later in a week :dancers:

**Comment by phongvcao** [comment]
I don't think having a separate version of VimScript-only is a good idea at this point. VimScript is not as flexible as Python and requires extra care from my part. This is a good idea though but I just don't want to add extra complexity. Thanks for the Pull Request.

**Pull request closed without merging**
